<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-11-06 19:13
=======
# Generated by Django 5.2.8 on 2025-11-11 08:07
>>>>>>> cb847aad9eb7755ea954410f144f02b6a187a963

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_app', '0006_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/images/'),
        ),
    ]
