# Generated by Django 5.2.7 on 2025-11-21 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_app', '0012_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_delivery',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
