# Generated by Django 5.2.7 on 2025-11-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hc_app', '0014_order_buyer_city_order_buyer_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_country',
            field=models.CharField(default='PH', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_street',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
